apiVersion: chainsaw.kyverno.io/v1alpha1
kind: Configuration
metadata:
  name: attune-e2e
spec:
  timeouts:
    apply: 30s
    assert: 2m
    cleanup: 5m
    delete: 2m
    error: 30s
    exec: 5m
  failFast: false
  parallel: 4
  skipDelete: false
  forceTerminationGracePeriod: 10s
