apiVersion: chainsaw.kyverno.io/v1alpha1
kind: Configuration
metadata:
  name: kube-rightsize-e2e
spec:
  timeouts:
    apply: 30s
    assert: 2m
    cleanup: 30s
    delete: 30s
    error: 30s
    exec: 30s
  failFast: false
  parallel: 2
  skipDelete: false
  forceTerminationGracePeriod: 10s
