---
version: 2
builds:
  - id: manager
    main: ./cmd/manager
    binary: manager
    goos: [linux]
    goarch: [amd64, arm64]
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}
  - id: kubectl-rightsize
    main: ./cmd/kubectl-rightsize
    binary: kubectl-rightsize
    goos: [linux, darwin]
    goarch: [amd64, arm64]
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
archives:
  - id: kubectl-plugin
    builds: [kubectl-rightsize]
    name_template: "kubectl-rightsize_{{ .Os }}_{{ .Arch }}"
changelog:
  use: github-native