---
version: 2
dist: goreleaser-dist
builds:
  - id: manager
    main: ./cmd/manager
    binary: manager
    goos: [linux]
    goarch: [amd64, arm64, arm, ppc64le, s390x]
    goarm: ["7"]
    flags:
      - -trimpath
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}
  - id: kubectl-attune
    main: ./cmd/kubectl-attune
    binary: kubectl-attune
    goos: [linux, darwin]
    goarch: [amd64, arm64, arm, ppc64le, s390x]
    goarm: ["7"]
    ignore:
      - goos: darwin
        goarch: arm
      - goos: darwin
        goarch: ppc64le
      - goos: darwin
        goarch: s390x
    flags:
      - -trimpath
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
archives:
  - id: kubectl-plugin
    ids: [kubectl-attune]
    name_template: "kubectl-attune_{{ .Os }}_{{ .Arch }}"
checksum:
  name_template: checksums.txt
changelog:
  use: github-native