exclude = [
  "localhost",
  "127\\.0\\.0\\.1",
  "0\\.0\\.0\\.0",
  "example\\.com",
  "medium\\.com",
  "hub\\.docker\\.com",
  "securityscorecards\\.dev",
]
exclude_loopback = true
max_concurrency = 8
timeout = 30
max_retries = 3
retry_wait_time = 5
