#!/usr/bin/env bash
# Copyright 2026 kube-rightsize Authors
# SPDX-License-Identifier: Apache-2.0
#
# Verify that the Helm chart ClusterRole rules match the kustomize-generated
# config/rbac/role.yaml. Catches RBAC desync when kubebuilder markers are
# updated but the Helm template is not.

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

KUSTOMIZE_ROLE="$REPO_ROOT/config/rbac/role.yaml"
HELM_CHART="$REPO_ROOT/charts/kube-rightsize"

if ! command -v yq &>/dev/null; then
  echo "ERROR: yq is required but not installed" >&2
  exit 1
fi

# Normalize rules by expanding to sorted (apiGroup, resource, verb) triples.
# This handles structural differences (kustomize merges resources with same
# apiGroup+verbs; Helm keeps them separate for readability).
normalize_rules() {
  jq -S '[ .[] | .apiGroups[] as $g | .resources[] as $r | .verbs[] as $v |
    "\($g)/\($r)/\($v)" ] | unique | .[]' | sort
}

# Extract rules from kustomize role.yaml.
kustomize_rules=$(yq -o=json '.rules' "$KUSTOMIZE_ROLE" | normalize_rules)

# Render Helm template and extract ClusterRole rules.
helm_output=$(helm template rbac-check "$HELM_CHART" \
  --set webhooks.enabled=false \
  --show-only templates/clusterrole.yaml 2>/dev/null)

helm_rules=$(echo "$helm_output" | yq -o=json '.rules' | normalize_rules)

if [ "$kustomize_rules" = "$helm_rules" ]; then
  echo "OK: Helm chart RBAC rules match kustomize config/rbac/role.yaml"
  exit 0
fi

echo "ERROR: Helm chart ClusterRole rules do not match config/rbac/role.yaml" >&2
echo "" >&2
echo "--- kustomize (config/rbac/role.yaml)" >&2
echo "+++ helm (charts/kube-rightsize/templates/clusterrole.yaml)" >&2
diff <(echo "$kustomize_rules") <(echo "$helm_rules") >&2 || true
echo "" >&2
echo "Fix: update charts/kube-rightsize/templates/clusterrole.yaml to match" >&2
echo "     the rules generated by 'make manifests' in config/rbac/role.yaml." >&2
exit 1