{{- if .Values.prometheusAuth.queryServiceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.prometheusAuth.queryServiceAccount.name | default (printf "%s-prometheus-query" (include "attune.fullname" .)) }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "attune.labels" . | nindent 4 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "attune.fullname" . }}-query-token
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "attune.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["serviceaccounts/token"]
    resourceNames:
      - {{ .Values.prometheusAuth.queryServiceAccount.name | default (printf "%s-prometheus-query" (include "attune.fullname" .)) }}
    verbs: ["create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "attune.fullname" . }}-query-token
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "attune.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "attune.fullname" . }}-query-token
subjects:
  - kind: ServiceAccount
    name: {{ include "attune.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}
