apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-server
  namespace: myapp
  labels:
    app: api-server
    tier: api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: api-server
  template:
    metadata:
      labels:
        app: api-server
        tier: api
    spec:
      containers:
        - name: api
          image: registry.k8s.io/pause:3.9
          resources:
            requests:
              cpu: 500m
              memory: 512Mi
            limits:
              cpu: "1"
              memory: 1Gi
          ports:
            - containerPort: 8080