apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: kube-rightsize
  namespace: kube-rightsize-system
  labels:
    app.kubernetes.io/name: kube-rightsize
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: kube-rightsize
  endpoints:
    - port: metrics
      interval: 30s