---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - bases/attune.io_attunepolicies.yaml
  - bases/attune.io_attunedefaults.yaml
  - bases/attune.io_attunenamespacedefaults.yaml
