name: Sync Docker Hub README

on:
  workflow_dispatch: {}

permissions:
  contents: read

jobs:
  sync:
    name: Sync README
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - name: Update Docker Hub description
        uses: peter-evans/dockerhub-description@1b9a80c056b620d92cedb9d9b5a223409c68ddfa # v5.0.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: attuneio/attune
          readme-filepath: docker/README.md
          short-description: "Safe, in-place Kubernetes pod resource right-sizing. VPA done right."